# Generated by Django 3.0.3 on 2020-05-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Number_of_items',
            field=models.IntegerField(default=1),
        ),
    ]
