# Generated by Django 3.0.3 on 2020-05-04 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_cart_number_of_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Number_of_items',
            new_name='Number_of_products',
        ),
    ]
